### ISSUE TITLE
Merging To Do Tasks extension

### ISSUE THREAD

**Issue by sandy081** [walllk/vsc-tasks#3]
Hi @walllk 

I published an extension [To Do Tasks](https://marketplace.visualstudio.com/items?itemName=sandy081.todotasks) last week for organizing todo tasks using VS Code.. After, while I was browsing extensions in MP (Market Place), I came across vsc-tasks extension from you which is pretty much similar to what I have done.

I have similar actions as you have like creating a task, completing and deleting. I also have theming support (decoration), tagging and etc., Please refer to the extension in MP and [To Do Tasks](https://github.com/sandy081/vscode-todotasks) in Github for more information.

Here is my proposal, probably it would be a good idea to merge both of our extensions to a single one to avoid duplicates. Moving forward, either you or I can make a PR and merge them. I am open to  suggestions.

Thanks
Sandeep Somavarapu

**Comment by walllk** [comment]
Hi @sandy081 

your extension looks great so far, good job on that. I have no problem in merging them both to one. Since yours looks a lot mature than mine, I suggest going ahead from your extension would be better. What do you think?

Jan

EDIT: As far as I can see in your extension. Adding Tasks below or above current line + keybindings (Alt-Enter // Alt-Shift-Enter) would be a great feature for listing ToDo's

**Comment by jrz** [comment]
I tried both, and I've used plaintasks in sublime.
I like this one better because it works ony any file (markdown), and it didn't crash on me.

**Comment by walllk** [comment]
Thanks @jrz
